######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 22 18:17:46 2019
######################################################################

QT += testlib
TEMPLATE = app
TARGET = tutorial1
INCLUDEPATH += .

# Input
SOURCES += tutorial1.cpp
